### ISSUE TITLE
USER STORY: Cast vote on poll

### ISSUE THREAD

**Issue by lorrainescanlon** [lorrainescanlon/love-running#1]
In order to **vote on best running time and best running track** as a **user**, I can **select my option from a list of options**

# Acceptance Criteria:

* Acceptance Criteria 1: The list of running time options should appear as a dropdown list.
* Acceptance Criteria 2: The list of running track options should appear as another dropdown list.

# Tasks
- [ ] Design and create a form element to contain the poll items in HTML and CSS
- [ ] Create a dropdown lists populated with the options the user will choose from
- [ ] Create a submit button to return the user selections for analysis
