### ISSUE TITLE
USER STORY: Provide feedback

### ISSUE THREAD

**Issue by lorrainescanlon** [lorrainescanlon/love-running#2]
In order to **provide feedback and comment** as a **user**, I can **have the option to do so anonymously**

# Acceptance Criteria:

* Acceptance Criteria 1: There should be a sizeable input text box to provide feedback and comments.
* Acceptance Criteria 2: There should be another optional input text box to provide your name is you so wish. 

# Tasks
- [ ] Create an input box for the user to leave comments or feedback, add placeholder text 'please write feedback here, limit (number) of characters'
- [ ] Create an input box where a user can provide their name with placeholder text 'optional'
- [ ] Create a submit button so that the data can be used for further analysis
