### ISSUE TITLE
DEFECT: Sign Up button problem on Andriod tablet devices

### ISSUE THREAD

**Issue by lorrainescanlon** [lorrainescanlon/love-running#4]
**Sign Up button** not appearing properly on **Android tablet devices**.

# Acceptance Criteria
* Fix so that sign up button appears and functions correctly on all devices and platforms 

# Tasks
- [ ] Test to replicate problem
- [ ] Update code to fix display problem
- [ ] Test efficiently to ensure that fix has worked
