### ISSUE TITLE
USER STORY: Signup with Social Media Networks

### ISSUE THREAD

**Issue by lorrainescanlon** [lorrainescanlon/love-running#5]
In order to **increase signup rate** a **user** can **signup with social media networks**

# Acceptance Criteria
* Provide an option for users to register using their existing social media network accounts 
* Include relevant social media accounts as options

# Tasks
- [ ] Create an option on the form to register using Social Media Networks 
- [ ] Develop backend code to allow this process
- [ ] Test sufficiently to ensure that this feature works correctly
