### ISSUE TITLE
USER STORY: SMS reminder

### ISSUE THREAD

**Issue by lorrainescanlon** [lorrainescanlon/love-running#6]
In order to **not miss a run** as a **user**, I can **receive an SMS reminder 60 minutes before**

# Acceptance Criteria
* Give users an option at signup to chose SMS reminders 
* Reminders should include time, date and location of run
* Users should have an option to opt out of reminders in their account

# Tasks
- [ ] Update registration form with option for SMS 
- [ ] Validate phone number given
- [ ] Update user account section with option to unsubscribe to SMS reminders
- [ ] Develop backend to handle SMS
- [ ] Test feature appropriately
