### ISSUE TITLE
USER STORY: Record run and share on Social Media

### ISSUE THREAD

**Issue by lorrainescanlon** [lorrainescanlon/love-running#7]
In order to **record my run** as a **user**, I can **mark my run as complete, provide feedback and share to social media**

# Acceptance Criteria
* User can mark as complete their run
* Users have an option to provide feedback on their run 
* Users can share this data to social media

# Tasks
- [ ] Create complete button within app
- [ ] Create text box where user can enter feedback
- [ ] Create option to share to social media networks
- [ ] Create submit button
- [ ] Test feature
