### ISSUE TITLE
USER STORY: Display runner tweets

### ISSUE THREAD

**Issue by lorrainescanlon** [lorrainescanlon/love-running#9]
In order to **keep up with other users** , I can **view Love Running tweets on the homepage**

# Acceptance Criteria
* Users can tweet using the Love Running hashtag
* A timeline is included on the homepage to display tweets

# Tasks
- [ ] Create twitter hashtag
- [ ] Create timeline feature on the homepage to display tweets
- [ ] Ensure timeline is updated
- [ ] Test feature
